### ISSUE TITLE
Please add bank Rabobank (NL)

### ISSUE THREAD

**Issue by bosel** [niknow/BankCSVtoQif#7]
[rabo.csv](https://github.com/niknow/BankCSVtoQif/files/357624/rabo.txt)

Would you please add support for Rabobank? I did give it a go myself, but i fear at least one additional feature might be needed (or at least, I could not find a possibility to set the source bank account, which is required as one csv contains transactions from several accounts).

A few things to note:

field 1: source account (multiple)
field 4: determines debet or credit (either "C" or "D"), amount (field 5) always positive

full description of the cvs format can be found here https://www.rabobank.nl/images/formaatbeschrijving_csv_kommagescheiden_nieuw_29539176.pdf

Thanks!

**Comment by niknow** [comment]
Hi,

thanks a lot for your contribution. I've added support for parsing Rabobank in the commit above. The description is taken from fields 10 and 11. 

To support multiple source accounts it would indeed be neccessary to add that functionality to the tool as a whole. But since qif and gnucash support this, bankcsvtoqif should support it too. I'll put that on a list for upcoming features. 

In the meantime: Is it not possible to get the transaction data for each source account in a separate csv file from Rabo? Then one could import them separately onto the correct account.

**Comment by niknow** [comment]
I've just merged a bunch of commits to support parsing the source account. Please try out, if it works for you now. (If not, feel free to open an issue.)

**Comment by bosel** [comment]
Initial test looks good, 

thanks!
